require('test.JobHandlers.RDM')
require('test.JobHandlers.PLD')
require('test.JobHandlers.BRD')
require('test.JobHandlers.NIN')
require('test.JobHandlers.COR')
require('test.JobHandlers.SCH')
require('test.JobHandlers.GEO')