---@meta
---@class modes
---@field generatePackerConfig function Generates a packer config from your sets table and modes
---@field registerKeybinds function handles all keybind setup for Smart
---@field enableWeaponGroups function turns on weapon groups for this profile
---@field enableSecondaryGroups function turns on secondary groups for this profile
---@field enableOverrideLayers function turns on override layers for this profile
---@field registerSets fun(mode: string, sets: sets) registers an extra sets table (for overrides that require many changes)
---@field registerWeaponGroup fun(group: string, set: {Main:string?, Sub:string?, Range:string?, Ammo:string?}) registers a weapon group
---@field registerSecondaryGroup fun(group: string, set: {Main:string?, Sub:string?, Range:string?, Ammo:string?}) registers a secondary group
---@field registerOverride fun(layerName: string, sets: sets, stateName: string?, keybind: string?) registers an override layer. Layers will be applied in the same order that they are declared in your profile.
---@field getSets function returns the appropriate sets table with all overrides applied for the current mode state
---@field getWeaponGroup function returns the set table for the currently active weapon group
---@field getSecondaryGroup function returns the set table for the currently active weapon group
---@field setActiveMode fun(key: string) sets the currently active mode (see: registerSets) to key, if key is a registered mode.
---@field setActiveWeaponGroup fun(key: string) sets the currently active weapon group to key, if key is a registered weapon group.
---@field setActiveSecondaryGroup fun(key: string) sets the currently active secondary group to key, if key is a registered secondary group
---@field nextMode function changes the currently active mode to the next one in the mode list. (see: registerSets)
---@field nextWeaponGroup function changes the currently active weapon group to the next one in the group list. will loop around at the end.
---@field nextSecondaryGroup function changes the currently active secondary group to the next one in the group list. will loop around at the end.
---@field nextOverrideState fun(layer: string) changes the override state of the provided layer to the next one in its list.
---@field setWindowPosX fun(x: number) moves the mode display widget to the specified X coordinate on screen
---@field setWindowPosY fun(y: number) moves the mode display widget to the specified Y coordinate on screen
---@field setWindowVisibility fun(b: boolean) changes whether the mode display widget is visible
---@field toggleWindowVisibility function toggles the visibility of the mode display widget
---@field initializeWindow function
---@field applyOverrides fun(baseSet: set, outerKey:string, innerKey:string, secondaryInnerKey:string?)