---@alias actionHandler fun(action:Action, sets:sets): boolean
---actionHandler returns true if an action was handled, false otherwise.

---@meta
---@class jobHandler
---@field default fun(sets:sets, status:EntityStatus)?
---@field ability actionHandler?
---@field precast actionHandler?
---@field midcast actionHandler?
---@field preshot actionHandler?
---@field midshot actionHandler?
